################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/lib/FreeRTOS/Source/croutine.c \
../src/lib/FreeRTOS/Source/event_groups.c \
../src/lib/FreeRTOS/Source/list.c \
../src/lib/FreeRTOS/Source/queue.c \
../src/lib/FreeRTOS/Source/stream_buffer.c \
../src/lib/FreeRTOS/Source/tasks.c \
../src/lib/FreeRTOS/Source/timers.c 

OBJS += \
./src/lib/FreeRTOS/Source/croutine.o \
./src/lib/FreeRTOS/Source/event_groups.o \
./src/lib/FreeRTOS/Source/list.o \
./src/lib/FreeRTOS/Source/queue.o \
./src/lib/FreeRTOS/Source/stream_buffer.o \
./src/lib/FreeRTOS/Source/tasks.o \
./src/lib/FreeRTOS/Source/timers.o 

C_DEPS += \
./src/lib/FreeRTOS/Source/croutine.d \
./src/lib/FreeRTOS/Source/event_groups.d \
./src/lib/FreeRTOS/Source/list.d \
./src/lib/FreeRTOS/Source/queue.d \
./src/lib/FreeRTOS/Source/stream_buffer.d \
./src/lib/FreeRTOS/Source/tasks.d \
./src/lib/FreeRTOS/Source/timers.d 


# Each subdirectory must supply rules for building sources it contributes
src/lib/FreeRTOS/Source/croutine.o: ../src/lib/FreeRTOS/Source/croutine.c src/lib/FreeRTOS/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F103xB -DUSER_VECT_TAB_ADDRESS -c -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/ap" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/bsp" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/hw" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/CMSIS/Include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/STM32F1xx_HAL_Driver/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common/hw/include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/USB_DEVICE/App" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/USB_DEVICE/Target" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common/core" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/CMSIS_RTOS" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/portable/GCC/ARM_CM3" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"src/lib/FreeRTOS/Source/croutine.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
src/lib/FreeRTOS/Source/event_groups.o: ../src/lib/FreeRTOS/Source/event_groups.c src/lib/FreeRTOS/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F103xB -DUSER_VECT_TAB_ADDRESS -c -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/ap" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/bsp" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/hw" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/CMSIS/Include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/STM32F1xx_HAL_Driver/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common/hw/include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/USB_DEVICE/App" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/USB_DEVICE/Target" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common/core" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/CMSIS_RTOS" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/portable/GCC/ARM_CM3" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"src/lib/FreeRTOS/Source/event_groups.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
src/lib/FreeRTOS/Source/list.o: ../src/lib/FreeRTOS/Source/list.c src/lib/FreeRTOS/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F103xB -DUSER_VECT_TAB_ADDRESS -c -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/ap" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/bsp" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/hw" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/CMSIS/Include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/STM32F1xx_HAL_Driver/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common/hw/include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/USB_DEVICE/App" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/USB_DEVICE/Target" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common/core" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/CMSIS_RTOS" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/portable/GCC/ARM_CM3" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"src/lib/FreeRTOS/Source/list.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
src/lib/FreeRTOS/Source/queue.o: ../src/lib/FreeRTOS/Source/queue.c src/lib/FreeRTOS/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F103xB -DUSER_VECT_TAB_ADDRESS -c -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/ap" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/bsp" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/hw" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/CMSIS/Include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/STM32F1xx_HAL_Driver/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common/hw/include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/USB_DEVICE/App" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/USB_DEVICE/Target" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common/core" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/CMSIS_RTOS" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/portable/GCC/ARM_CM3" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"src/lib/FreeRTOS/Source/queue.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
src/lib/FreeRTOS/Source/stream_buffer.o: ../src/lib/FreeRTOS/Source/stream_buffer.c src/lib/FreeRTOS/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F103xB -DUSER_VECT_TAB_ADDRESS -c -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/ap" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/bsp" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/hw" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/CMSIS/Include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/STM32F1xx_HAL_Driver/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common/hw/include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/USB_DEVICE/App" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/USB_DEVICE/Target" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common/core" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/CMSIS_RTOS" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/portable/GCC/ARM_CM3" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"src/lib/FreeRTOS/Source/stream_buffer.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
src/lib/FreeRTOS/Source/tasks.o: ../src/lib/FreeRTOS/Source/tasks.c src/lib/FreeRTOS/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F103xB -DUSER_VECT_TAB_ADDRESS -c -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/ap" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/bsp" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/hw" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/CMSIS/Include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/STM32F1xx_HAL_Driver/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common/hw/include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/USB_DEVICE/App" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/USB_DEVICE/Target" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common/core" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/CMSIS_RTOS" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/portable/GCC/ARM_CM3" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"src/lib/FreeRTOS/Source/tasks.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
src/lib/FreeRTOS/Source/timers.o: ../src/lib/FreeRTOS/Source/timers.c src/lib/FreeRTOS/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F103xB -DUSER_VECT_TAB_ADDRESS -c -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/ap" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/bsp" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/hw" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/CMSIS/Include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Drivers/STM32F1xx_HAL_Driver/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common/hw/include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/USB_DEVICE/App" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/cube_remind_f103/USB_DEVICE/Target" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/common/core" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/CMSIS_RTOS" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/include" -I"C:/STM32 Coding files/remind_fw103/remind_arm/stm32f103_remind/src/lib/FreeRTOS/Source/portable/GCC/ARM_CM3" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"src/lib/FreeRTOS/Source/timers.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

